### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by ashwin3454** [reniyal-otpless/otpless-shopify-demo#1]
is this login for store owner or customer checkout login?

**Comment by reniyal-otpless** [comment]
its for customer login. [official documentation](https://otpless.com/docs/frontend-sdks/plugins/shopify/integration)

**Comment by reniyal-otpless** [comment]
[OTPless plugin](https://apps.shopify.com/otpless-whatsapp-login) is for customer login.

For More info, visit [Otpless.com](https://otpless.com).
Check out [Official documentation](https://otpless.com/docs/frontend-sdks/plugins/shopify/integration)

**Comment by reniyal-otpless** [comment]
[OTPless plugin](https://apps.shopify.com/otpless-whatsapp-login) is for customer authentication.

For More info, visit [Otpless.com](https://otpless.com).
Check out [Official documentation](https://otpless.com/docs/frontend-sdks/plugins/shopify/integration)
